### ISSUE TITLE
Allow TLS connection with self-sigend certificates

### ISSUE THREAD

**Issue by movd** [ricoberger/dash#12]
It would be useful to allow for the skipping of TLS verification for Prometheus data sources similar to Grafana's "Skip TLS Verify" parameter.

**Comment by ricoberger** [comment]
Hi @movd, this should be supported by version [1.0.1](https://github.com/ricoberger/dash/releases/tag/1.0.1).

The documentation can be found here: https://github.com/ricoberger/dash/wiki/Prometheus
